<?php
return [
    'api_version' => '2025-01',
    'api_market_version' => '2025-01',
    'scopes' => [
        'read_themes',
        'read_orders',
        'read_products',
        'read_discounts',
        'write_discounts',
        'read_price_rules',
        'write_price_rules',
        // 'read_script_tags',
        // 'write_script_tags',
        // 'read_discounts',
        // 'write_discounts',
        // 'read_translations',
        // 'write_translations',
        // 'read_legal_policies',
        // 'read_shipping',
        // 'write_shipping',
        // 'read_files',
        // 'write_files',
        // 'read_markets',
    ],

    // English, Chinese, Russian, Portuguese, Spanish, French, German, Italian, Dutch, Turkish, Japanese, Korean, Thai, Vietnamese, Arabic, Hebrew, Polish
    "popular_languages_code" => ["en", "zh-CN", "zh-TW", "ru", "pt-BR", "pt-PT", "es", "fr", "de", "it", "nl", "tr", "ja", "ko", "th", "vi", "ar", "he", "pl"],

    "popular_languages_code_and_name" => [
        [
            'isoCode' => 'en',
            'name' => 'English'
        ],
        [
            'isoCode' => 'zh-CN',
            'name' => 'Chinese (Simplified)'
        ],
        [
            'isoCode' => 'zh-TW',
            'name' => 'Chinese (Traditional)'
        ],
        [
            'isoCode' => 'ru',
            'name' => 'Russian'
        ],
        [
            'isoCode' => 'pt-BR',
            'name' => 'Portuguese (Brazil)'
        ],
        [
            'isoCode' => 'pt-PT',
            'name' => 'Portuguese (Portugal)'
        ],
        [
            'isoCode' => 'es',
            'name' => 'Spanish'
        ],
        [
            'isoCode' => 'fr',
            'name' => 'French'
        ],
        [
            'isoCode' => 'de',
            'name' => 'German'
        ],
        [
            'isoCode' => 'it',
            'name' => 'Italian'
        ],
        [
            'isoCode' => 'nl',
            'name' => 'Dutch'
        ],
        [
            'isoCode' => 'tr',
            'name' => 'Turkish'
        ],
        [
            'isoCode' => 'ja',
            'name' => 'Japanese'
        ],
        [
            'isoCode' => 'ko',
            'name' => 'Korean'
        ],
        [
            'isoCode' => 'th',
            'name' => 'Thai'
        ],
        [
            'isoCode' => 'vi',
            'name' => 'Vietnamese'
        ],
        [
            'isoCode' => 'ar',
            'name' => 'Arabic'
        ],
        [
            'isoCode' => 'he',
            'name' => 'Hebrew'
        ],
        [
            'isoCode' => 'pl',
            'name' => 'Polish'
        ],
    ],
    "popular_currencies_code" => ["USD", "EUR", "JPY", "GBP", "AUD", "CAD", "CHF", "CNY", "HKD", "NZD", "SEK", "KRW", "SGD", "NOK", "MXN", "INR", "RUB", "ZAR", "TRY", "BRL", "TWD", "DKK", "PLN", "THB", "IDR", "HUF", "CZK", "ILS", "CLP", "PHP", "COP", "SAR", "MYR", "RON"],
    "hieroglyphics_languages" => [
        "ar",
        "zh-CN",
        "zh-TW",
        "zh",
        "he",
        "ja",
        "ko",
        "th",
        "am",
        "hy",
        "as",
        "my",
        "ce",
        "dz",
        "ka",
        "gu",
        "ha",
        "hi",
        "kn",
        "ks",
        "kk",
        "km",
        "ky",
        "lo",
        "ml",
        "mr",
        "ne",
        "or",
        "os",
        "ps",
        "fa",
        "pa",
        "sd",
        "si",
        "ta",
        "te",
        "bo",
        "ti",
        "ur",
        "ug",
        "yi"
    ],
    'media_upload_type' => ['jpg', 'gif', 'png', 'jpeg'],
    'language_google_support_translate' => [
        "af",
        "sq",
        "am",
        "ar",
        "hy",
        "az",
        "eu",
        "be",
        "bn",
        "bs",
        "bg",
        "ca",
        "ceb",
        "zh-CN",
        "zh-TW",
        "co",
        "hr",
        "cs",
        "da",
        "nl",
        "en",
        "eo",
        "et",
        "fi",
        "fr",
        "fy",
        "gl",
        "ka",
        "de",
        "el",
        "gu",
        "ht",
        "ha",
        "haw",
        "he",
        "hi",
        "hmn",
        "hu",
        "is",
        "ig",
        "id",
        "ga",
        "it",
        "ja",
        "jv",
        "kn",
        "kk",
        "km",
        "rw",
        "ko",
        "ku",
        "ky",
        "lo",
        "la",
        "lv",
        "lt",
        "lb",
        "mk",
        "mg",
        "ms",
        "ml",
        "mt",
        "mi",
        "mr",
        "mn",
        "my",
        "ne",
        "no",
        "ny",
        "or",
        "ps",
        "fa",
        "pl",
        "pt",
        "pa",
        "ro",
        "ru",
        "sm",
        "gd",
        "sr",
        "st",
        "sn",
        "sd",
        "si",
        "sk",
        "sl",
        "so",
        "es",
        "su",
        "sw",
        "sv",
        "tl",
        "tg",
        "ta",
        "tt",
        "te",
        "th",
        "tr",
        "tk",
        "uk",
        "ur",
        "ug",
        "uz",
        "vi",
        "cy",
        "xh",
        "yi",
        "yo",
        "zu",
        'pt-BR',
        'pt-PT',
        'nn',
        'nb',
        'zh',
        'lt-LT',
        'ro-RO',
        'es-US'
    ],
];
